### ISSUE TITLE
public_member_api_docs doesn't recommend?

### ISSUE THREAD

**Issue by shinriyo** [mono0926/pedantic_mono#1]
It is a good idea cause I hoped severely lint for Dart like coding.
But, It doesn't have the option.
https://dart-lang.github.io/linter/lints/public_member_api_docs.html
public_member_api_docs doesn't recommend?

* 日本語

Googleが推奨している厳しめのDartっぽいコーディングできるものが欲しかったので、いいと思いました。
しかし、 `public_member_api_docs` が入ってないのですが、これは推奨されてないのでしょうか？

**Comment by mono0926** [comment]
I feel it is too strict for me.
I think writing all public member api docs is not alway necessary for application code.

Of course, you can feel free to add `public_member_api_docs` on your choice 👌
